# Generated by Django 4.2.5 on 2023-10-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('profession', models.CharField(max_length=500)),
                ('education', models.CharField(max_length=500)),
                ('course', models.CharField(max_length=500)),
                ('photo', models.ImageField(default='No images', upload_to='images/')),
                ('transcript', models.ImageField(default='No images', upload_to='images/')),
            ],
        ),
    ]
