# Generated by Django 4.2.5 on 2023-10-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo_user',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
