# Generated by Django 4.2.5 on 2023-10-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_demo_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo_user',
            name='video',
            field=models.FileField(default='No Videos', upload_to='videos/'),
        ),
    ]
