# Generated by Django 4.2.5 on 2023-10-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_alter_demo_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo_user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
