# Generated by Django 4.2.5 on 2023-10-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('confirmpassword', models.CharField(max_length=255)),
                ('selected_gender', models.CharField(max_length=10)),
                ('selected_options', models.CharField(max_length=255)),
                ('selected_checkbox', models.BooleanField(default=False)),
            ],
        ),
    ]
